Skip to contentNew Project – Vercel
Changelog
Help
Docs

New Project
importing from GitHub

Arjun9234/CRM
master
Choose where you want to create the project and give it a name.

Vercel Team

arjun9234's projects
Hobby
Slash Divider
Project Name
crm
Framework Preset
Framework logo
Next.js
Root Directory
./
Key
EXAMPLE_NAME
Value
I9JU23NF394R6HH
GEMINI_API_KEY
AIzaSyCI9cGFYL-O4_WTR5MVosZ1v5J9b1MdzMc
NEXT_PUBLIC_FIREBASE_API_KEY
AIzaSyC5PSA8E3XsDwVVmfEhK82w8vzL5WZpDQ0
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
miniature-genius.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID
miniature-genius
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
miniature-genius.firebasestorage.app
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
172077047833
NEXT_PUBLIC_FIREBASE_APP_ID
1:172077047833:web:549da43e7f7928c5c6ca88
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
G-VKS1BBS4NB
MONGODB_URI
mongodb://localhost:27017/engagesphere
JWT_SECRET
017313bf-8445-4202-8684-93e4193db33f
SERVER_PORT
5000
Tip: Paste an .env above to populate the form. Learn more

Deployment
Deployment failed with error.
Build Logs
Exiting build container
54s
Find in logs
CtrlF
 140 |   }
 141 | }
     : ^
 142 |
 143 |
 144 | const customerStatusOptions: CustomerStatus[] = ['Active', 'Lead', 'Inactive', 'New', 'Archived'];
     `----
Caused by:
    Syntax Error
Import trace for requested module:
./src/app/customers/page.tsx
> Build failed because of webpack errors
Error: Command "npm run build" exited with 1
Exiting build container
Deployment Summary
Assigning Custom Domains
now remove that dummy data store - 80a502
Import a different Git Repository →
Browse Templates →
Home
Docs
Guides
Help
Contact
All systems normal

Select a display theme:

system

light

dark
© 2025, Vercel Inc.